### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -S target -L crate,statics` and `typos --format brief`.

### CODE REVIEW

**Comment by chase-manning** [comment]
@kianmeng Thanks so much for the PR! 😄

**Comment by kianmeng** [comment]
@chase-manning Should we add this as job to the CI pipeline?

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by chase-manning** [comment]
> @chase-manning Should we add this as job to the CI pipeline?

@kianmeng Great idea!! Would you like to raise a PR for this or should i? 😄

**Pull request merged**
